//ORDERS TYPES
export const ADD_TO_ORDER = "ADD_TO_CART";
export const REMOVE_FROM_ORDER = "REMOVE_FROM_CART";
export const ADD_ONE_TO_ORDER = "ADD_ONE_TO_CART";
export const REMOVE__ONE_FROM_ORDER = "REMOVE_ONE_FROM_CART";
export const CLEAR_ORDER = "CLEAR_ORDER";

//CRUDs PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
