//Interaction product and order TYPES
export const ADD_TO_ORDER = "ADD_TO_CART";
export const REMOVE_FROM_ORDER = "REMOVE_FROM_CART";
export const ADD_ONE_TO_ORDER = "ADD_ONE_TO_CART";
export const REMOVE__ONE_FROM_ORDER = "REMOVE_ONE_FROM_CART";
export const CLEAR_ORDER = "CLEAR_ORDER";

//CRUD PRODUCTS TYPES
export const GET_PRODUCTS_QUANTITY = "GET_PRODUCTS_QUANTITY";
export const GET_SOME_PRODUCTS = "GET_SOME_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

//CRUD ORDERS TYPES
export const GET_ORDERS_QUANTITY = "GET_ORDERS_QUANTITY";
export const GET_ORDERS = "GET_ORDER";
export const GET_ORDER = "GET_ORDER";
export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";

//PAGINATION TYPES
export const NEXT_PAGE_PRODUCT = "NEXT_PAGE_PRODUCT";
export const PREVIOUS_PAGE_PRODUCT = "PREVIOUS_PAGE_PRODUCT";
export const SELECT_PAGE_PRODUCT = "SELECT_PAGE_PRODUCT";
export const NEXT_PAGE_ORDER = "NEXT_PAGE_ORDER";
export const PREVIOUS_PAGE_ORDER = "PREVIOUS_PAGE_ORDER";
export const SELECT_PAGE_ORDER = "SELECT_PAGE_ORDER";

//SEARCHERS TYPES
export const GET_ORDERS_SEARCH_NAME = "GET_ORDERS_SEARCH_NAME";
export const GET_ORDERS_ORDER_BY = "GET_ORDERS_ORDER_BY";
export const GET_ORDERS_ORDER_BY_AD = "GET_ORDERS_ORDER_BY_AD";
export const GET_PRODUCT_SEARCH_NAME = "GET_PRODUCT_SEARCH_NAME";
export const GET_PRODUCT_ORDER_BY = "GET_PRODUCT_ORDER_BY";
export const GET_PRODUCT_ORDER_BY_AD = "GET_PRODUCT_ORDER_BY_AD";
